#@ load("@ytt:template", "template")

#@ load("/lib/cmake.lib.yml", "typical_cmake_builds", "cmake_boost_configuration")

---
#@ def build_args():
extra_cmake_args:
  - #@ template.replace(cmake_boost_configuration)
  #! TODO: this is really ugly hack to get the same value of QTC_SOURCE as legacy orchestra
  - -DQTC_SOURCE="$SOURCE_DIR/../qt-creator"
  - -DQTC_BUILD="$ORCHESTRA_ROOT"
build_dependencies:
  - cmake
dependencies:
  - toolchain/host/gcc
  - clang-release
  - caliban
  - ui/graphviz
  - ui/adaptagrams
  - ui/quickqanava
  - ui/qt-creator
  - autoupdater
use_asan: false
#@ end

---
#@ def _cold_revng_component():
repository: ui/cold-revng
builds: #@ typical_cmake_builds(**build_args())
#@ end

---
#@ cold_revng_component = _cold_revng_component()
