#@ load("@ytt:data", "data")
#@ load("@ytt:overlay", "overlay")
#@ load("/lib/create_component.lib.yml", "single_build_component")

#@ libpciaccess_source_url = "https://xorg.freedesktop.org/archive/individual/lib/libpciaccess-0.16.tar.gz"
#@ libdrm_source_url = "https://dri.freedesktop.org/libdrm/libdrm-2.4.102.tar.xz"

#@yaml/text-templated-strings
---
#@ def libpciaccess_args():
license: source/COPYING
configure: |
  mkdir -p "$BUILD_DIR"
  extract.sh --into "$BUILD_DIR/source" "(@= libpciaccess_source_url @)"
  cd "$BUILD_DIR"

  ./source/configure \
    --enable-shared \
    --disable-static \
    --prefix="$ORCHESTRA_ROOT" \
    LDFLAGS="(@= data.values.use_old_glibc_ldflags @) (@= data.values.modern_linker_flags @) -Wl,-rpath,$RPATH_PLACEHOLDER/lib" \
    CFLAGS="(@= data.values.use_old_glibc_cflags @)" \
    CC="cc -fuse-ld=gold"
build_system: make
build_dependencies:
  - host-c-toolchain
  - glibc
#@ end

#@yaml/text-templated-strings
---
#@ def libdrm_args():
license: source/RELEASING
configure: |
  mkdir -p "$BUILD_DIR"
  extract.sh --into "$BUILD_DIR/source" "(@= libdrm_source_url @)"

  find "$BUILD_DIR/source/" -name meson.build -exec sed -i "s|install\s*:\s*|install_rpath : '$RPATH_PLACEHOLDER/lib', \0|" {} \;

  CC=clang \
  meson setup \
    --buildtype plain \
    --libdir=lib \
    --prefix "$ORCHESTRA_ROOT" \
    --wrap-mode nodownload \
    -Dudev=false \
    -Dcairo-tests=false \
    -Damdgpu=true \
    -Dexynos=false \
    -Dfreedreno=false \
    -Dintel=true \
    -Dnouveau=false \
    -Domap=false \
    -Dradeon=true \
    -Dtegra=false \
    -Dvc4=false \
    -Detnaviv=false \
    -Dvmwgfx=false \
    -Dlibkms=false \
    -Dvalgrind=false \
    -Db_ndebug=true \
    -Dc_args="(@= data.values.use_old_glibc_cflags @) -w" \
    -Dc_link_args="(@= data.values.use_old_glibc_ldflags @) -fuse-ld=gold -L$ORCHESTRA_ROOT/lib -Wl,-z,origin -Wl,--enable-new-dtags -Wl,-rpath,$RPATH_PLACEHOLDER/lib" \
    "$BUILD_DIR" \
    "$BUILD_DIR/source"
build_system: ninja
build_dependencies:
  - host-c-toolchain
  - glibc
dependencies:
  - ui/libpciaccess
#@ end

#@overlay/match by=overlay.all, expects=1
#@overlay/match-child-defaults missing_ok=True
---
components:
  ui/libpciaccess: #@ single_build_component(**libpciaccess_args())
  ui/libdrm: #@ single_build_component(**libdrm_args())
