#@ load("@ytt:data", "data")
#@ load("@ytt:overlay", "overlay")
#@ load("/lib/create_component.lib.yml", "single_build_component")

#@ source_url = "https://sourceware.org/elfutils/ftp/0.181/elfutils-0.181.tar.bz2"

#@yaml/text-templated-strings
---
#@ def elfutils_args():
license: COPYING
configure: |
  mkdir -p "$BUILD_DIR"
  extract.sh --into "$BUILD_DIR" "(@= source_url @)"
  cd "$BUILD_DIR"
  ./configure \
    --disable-nls \
    --disable-thread-safety \
    --program-prefix=eu- \
    --with-zlib \
    --without-bzlib \
    --without-lzma \
    --prefix="$ORCHESTRA_ROOT" \
    --disable-debuginfod \
    --disable-libdebuginfod \
    CFLAGS="-Wno-error"
build_system: make
build_dependencies:
  - host-c-toolchain
  - glibc
dependencies:
  - zlib
#@ end

#@overlay/match by=overlay.all, expects=1
#@overlay/match-child-defaults missing_ok=True
---
components:
  elfutils: #@ single_build_component(**elfutils_args())
