#@ load("@ytt:data", "data")
#@ load("@ytt:overlay", "overlay")
#@ load("/lib/create_component.lib.yml", "single_build_component")

#@ source_url = "https://mirror.kumi.systems/gnu/libtool/libtool-2.4.6.tar.gz"

#@yaml/text-templated-strings
---
#@ def libltdl_args():
license: COPYING
configure: |
  mkdir -p "$BUILD_DIR"
  extract.sh --into "$BUILD_DIR" "(@= source_url @)"
  cd "$BUILD_DIR"
  ./configure \
    --enable-ltdl-install \
    --disable-static \
    --prefix="$ORCHESTRA_ROOT" \
    CFLAGS="-Wno-error"
build_system: make
build_dependencies:
  - host-c-toolchain
#@ end

#@overlay/match by=overlay.all, expects=1
#@overlay/match-child-defaults missing_ok=True
---
components:
  libltdl: #@ single_build_component(**libltdl_args())
