#@ load("@ytt:overlay", "overlay")
#@ load("@ytt:data", "data")
#@ load("/lib/cmake.lib.yml", "cmake_boost_configuration", "typical_cmake_builds")
#@ load("@ytt:template", "template")

---
#@ def build_args():
test: true
extra_cmake_args:
  - #@ template.replace(cmake_boost_configuration)
  - "-DLLVM_DIR=$ORCHESTRA_ROOT/lib64/llvm/llvm/lib/cmake/llvm"
extra_compiler_flags: #@ data.values.revng_extra_compiler_flags
build_dependencies:
  - host-cxx-toolchain
  - nodejs-support
  #! Note: we need this dependency for well-known-model binaries, which is a
  #! build-time dependency of revng.
  #! It would be possible to split off test/revng-qa to make it only build those
  #! binaries, but the benefits are not too big.
  - test/revng-qa
dependencies:
  - aws-sdk
  - boost
  - host-libcxx
  - llvm
  - qemu
  - revng-python-dependencies
  - toolchain/host/binutils
  - revng-js-prerequisites
  - glibc
  - gcc-runtime
  - libarchive
  - flamegraph
use_asan: false
post_install_script: |
  if [ "$RUN_TESTS" -eq 1 ]; then
    cd "$SOURCE_DIR"
    ./libexec/revng/check-conventions
  fi
#@ end

#@overlay/match by=overlay.all, expects=1
#@overlay/match-child-defaults missing_ok=True
---
components:
  revng:
    repository: revng
    license: LICENSE
    default_build: optimized
    test_triggers:
      - test/revng
    check_branch:
      - ./libexec/revng/check-conventions --force-format --HEAD --check-commit
      - orc shell -c revng cmake . && orc shell -c revng ninja revng-all-binaries
    builds: #@ typical_cmake_builds(**build_args())
