#@ load("@ytt:overlay", "overlay")
#@ load("/lib/create-component.lib.yml", "single_build_component")

#@ package_json_sha = "3ff791fa83fbd8247df7ab2bab2ee03413a198157240b4330c33cd615d94e378"

#@yaml/text-templated-strings
---
#@ def js_prerequisites_args():
dependencies:
  - nodejs
build_dependencies:
  - nodejs-support
configure: |
  mkdir -p "$BUILD_DIR"
  cd "$BUILD_DIR"
  cp -a "$ORCHESTRA_DOTDIR/support/revng-js-prerequisites-package.json" package.json

  # check that package.json has the right hash, this is to trigger a rebuild in orchestra
  # whenever we change the file
  echo '(@= package_json_sha @) package.json' | sha256sum -c -

  # Generate package lock
  npm.original install --package-lock-only --silent
  # Populate cache
  fetch-js-dependencies npm -o ./.cache
install: |
  cd "$BUILD_DIR"

  # copy all download packages to node_cache
  mkdir -p "${DESTDIR}${ORCHESTRA_ROOT}/share/node_cache"
  cp -a .cache/*.tgz "${DESTDIR}${ORCHESTRA_ROOT}/share/node_cache"

  # Install packages needed for building
  export ORCHESTRA_NODE_CACHE="$BUILD_DIR/.cache:$ORCHESTRA_NODE_CACHE"

  npm --global \
      --prefix="${DESTDIR}${ORCHESTRA_ROOT}" \
      install \
        prettier eslint lint-staged gts \
        eslint-plugin-node eslint-plugin-prettier \
        @typescript-eslint/eslint-plugin @typescript-eslint/parser
#@ end

#@overlay/match by=overlay.all, expects=1
#@overlay/match-child-defaults missing_ok=True
---
components:
  revng-js-prerequisites: #@ single_build_component(**js_prerequisites_args())
