#@ load("/lib/cmake.lib.yml", "cmake_boost_configuration", "typical_cmake_builds")

#@ load("/global_options.lib.yml", "options")

---
#@ def build_args():
extra_cmake_args: #@ cmake_boost_configuration
build_dependencies:
  - revng-qa
dependencies:
  - toolchain/host/gcc
  - llvm
  - qemu
  - boost
  - clang-release
use_asan: false
#@ end

---
#@ def _revng_component():
repository: revng
builds: #@ typical_cmake_builds(**build_args())
#@ end

---
#@ revng_component = _revng_component()
