#@ load("@ytt:overlay", "overlay")
#@ load("@ytt:data", "data")
#@ load("/lib/cmake.lib.yml", "cmake_boost_configuration", "typical_cmake_builds")

---
#@ def build_args():
test: true
extra_cmake_args: #@ cmake_boost_configuration
extra_compiler_flags: #@ data.values.revng_extra_compiler_flags
build_dependencies:
  - cmake
  - host-cxx-toolchain
  - revng-js-prerequisites
dependencies:
  - boost
  - host-libcxx
  - llvm
  - qemu
  - revng-python-dependencies
  - toolchain/host/binutils
use_asan: false
post_install_script: |
  if [ "$RUN_TESTS" -eq 1 ]; then
    cd "$SOURCE_DIR"
    ./libexec/revng/revng-check-conventions
  fi
#@ end

#@overlay/match by=overlay.all, expects=1
#@overlay/match-child-defaults missing_ok=True
---
components:
  revng:
    repository: revng
    license: LICENSE.md
    default_build: optimized
    test_triggers:
      - test/revng
    check_branch:
      - ./libexec/revng/revng-check-conventions --force-format --HEAD
      - orc shell -c revng cmake . && orc install revng
    builds: #@ typical_cmake_builds(**build_args())
