#@ load("@ytt:overlay", "overlay")
#@ load("/lib/create-component.lib.yml", "single_build_component")

#@yaml/text-templated-strings
---
#@ def uvloop_args():
#@ uvloop_version = "0.19.0"
#@ source_url = "https://github.com/MagicStack/uvloop/archive/refs/tags/v" + uvloop_version + ".tar.gz"
license: LICENSE-MIT
configure: |
  mkdir -p "$BUILD_DIR"
  extract.sh --into "$BUILD_DIR" (@= source_url @)
install: |
  cd "$BUILD_DIR"
  python setup.py \
    build_ext --use-system-libuv \
    install --compile --root "$DESTDIR"

  PYTHON_PACKAGES_DIR="$DESTDIR$ORCHESTRA_ROOT/share/orchestra/python-packages/"
  mkdir -p "$PYTHON_PACKAGES_DIR"
  echo "uvloop" > "$PYTHON_PACKAGES_DIR/uvloop.txt"
dependencies:
- python-base-packages
- libuv
- cython
build_dependencies:
- host-c-toolchain
#@ end

#@overlay/match by=overlay.all, expects=1
#@overlay/match-child-defaults missing_ok=True
---
components:
  uvloop: #@ single_build_component(**uvloop_args())
