#@ load("@ytt:overlay", "overlay")

#@overlay/match by=overlay.all, expects=1
#@overlay/match-child-defaults missing_ok=True
---
components:
  host-c-toolchain:
    builds:
      default:
        dependencies:
          - glibc
          - toolchain/host/binutils
          - clang-release
        install: exit 0
        configure: mkdir -p "$BUILD_DIR"

  host-cxx-toolchain:
    builds:
      default:
        dependencies:
          - glibc
          - toolchain/host/binutils
          - clang-release
        install: exit 0
        configure: mkdir -p "$BUILD_DIR"

  host-libcxx:
    builds:
      default:
        dependencies:
          - libcxx
          - toolchain/host/gcc
        install: exit 0
        configure: mkdir -p "$BUILD_DIR"
